pin "application"
pin "@hotwired/turbo-rails", to: "turbo.min.js"
pin "@hotwired/stimulus", to: "stimulus.min.js"
pin "@hotwired/stimulus-loading", to: "stimulus-loading.js"
pin "advanced_select/advanced_select_controller", to: "advanced_select/advanced_select_controller.js"
pin_all_from "app/javascript/controllers", under: "controllers"
